#Task 1

In [ ]:
print("Enter 5 numbers")
lst = []
for i in range(5):
  num = int(input())
  lst.append(num)
  print("Numbers in the list:",lst)

Enter 5 numbers
3
Numbers in the list: [3]
5
Numbers in the list: [3, 5]
34
Numbers in the list: [3, 5, 34]
-11
Numbers in the list: [3, 5, 34, -11]
0
Numbers in the list: [3, 5, 34, -11, 0]

#Task 2

In [ ]:
lst = [int(i) for i in input("Enter a list of numbers: ").split(', ')]
if len(lst)<=3:
  print("Not possible")
else:
  print(lst[2:-2])

Enter a list of numbers: 10, 20, 24, 25, 26, 35, 70
[24, 25, 26]

In [ ]:
s = input("Enter a list of numbers: ")

lst1 = s.split(", ")
lst2 = []
for i in lst1:
  lst2.append(int(i))
if len(lst2)<=3:
  print("Not possible")
else:
  print(lst2[2:-2])

Enter a list of numbers: 10, 20, 24, 25, 26, 35, 70
[24, 25, 26]

In [ ]:
s = input("Enter a list of numbers: ")
x = ''
lst1 = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    lst1.append(int(x))
    x=''
lst1.append(int(x))
if len(lst1)<4:
  print('Not possible')
else:
  print(lst1[2:-2])

Enter a list of numbers: 10, 20, 24, 25, 26, 35, 70
[24, 25, 26]

#Task 3

In [ ]:
print("Enter 5 numbers")
lst = []
for i in range(5):
  num = int(input())
  lst.append(num)
print("Printing values from the list in reverse order:")
for i in range(1,6):
  print(lst[-i])

Enter 5 numbers
5
-5
100
1
0
Printing values from the list in reverse order:
0
1
100
-5
5

#Task 4

In [ ]:
s = input("Enter a list: ")
s = s[1:-1]
lst1 = [int(i) for i in s.split(', ')]
lst2 = []
for i in lst1:
  lst2.append(i**2)
print(lst2)

Enter a list: [3, 5, 1, 6]
[9, 25, 1, 36]

In [ ]:
s = input("Enter a list: ")
s = s[1:-1]
s = s.split(", ")
lst1 = []
for i in s:
  lst1.append(int(i))
lst2 = []
for i in lst1:
  lst2.append(i**2)
print(lst2)

Enter a list: [3, 5, 1, 6]
[9, 25, 1, 36]

In [ ]:
s = input("Enter a list: ")
s = s[1:-1]

x = ''
lst1 = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    lst1.append(int(x))
    x=''
lst1.append(int(x))    
lst2 = []
for i in lst1:
  lst2.append(i**2)
print(lst2)

Enter a list: [3, 5, 1, 6]
[9, 25, 1, 36]

#Task 5

In [ ]:
s = input("Enter a list: ")
s = s[1:-1]
x=''
for i in s:
  if i != '"':
    x+=i
lst1 = [i for i in x.split(', ')]
print("Original List:",lst1)
lst2=[]
for i in lst1:
  if i!='':
    lst2.append(i)
print("Modified List:",lst2)

Enter a list: ["hey", "there", "", "what's", "", "up", "", "?"]
Original List: ['hey', 'there', '', "what's", '', 'up', '', '?']
Modified List: ['hey', 'there', "what's", 'up', '?']

In [ ]:
s = input("Enter a list: ")
s = s[1:-1]
x=''
for i in s:
  if i != '"':
    x+=i
y = x.split(", ")
lst1=[]
for i in y:
  lst1.append(i)
print("Original List:",lst1)
lst2=[]
for i in lst1:
  if i!='':
    lst2.append(i)
print("Modified List:",lst2)

Enter a list: ["hey", "there", "", "what's", "", "up", "", "?"]
Original List: ['hey', 'there', '', "what's", '', 'up', '', '?']
Modified List: ['hey', 'there', "what's", 'up', '?']

In [ ]:
s = input("Enter a list: ")
s = s[1:-1]

x = ''
lst1 = []
for i in s:
  if i!=',' and i!=' ' and i!='"':
    x+=i
  elif i==" ":
    lst1.append(x)
    x=''
lst1.append(x)
print("Original List:",lst1)
lst2=[]
for i in lst1:
  if i!='':
    lst2.append(i)
print("Modified List:",lst2)

Enter a list: ["hey", "there", "", "what's", "", "up", "", "?"]
Original List: ['hey', 'there', '', "what's", '', 'up', '', '?']
Modified List: ['hey', 'there', "what's", 'up', '?']

#Task 6

In [ ]:
lst = [int(i) for i in input("Enter a string containing numbers separated by commas: ").split(', ')]
print("My list:",lst)
max=0
for i in range(len(lst)):
  if i==0:
    max=lst[i]
  elif lst[i]>max:
    max=lst[i]
x=lst.index(max)
print(f'Largest number in the list is {max} which was found at index {x}.')

Enter a string containing numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Largest number in the list is 13 which was found at index 1.

In [ ]:
s = input("Enter a string containing numbers separated by commas: ")
lst1 = s.split(", ")
lst2 = []
for i in lst1:
  lst2.append(int(i))
print("My list:",lst2)
max=0
for i in range(len(lst2)):
  if i==0:
    max=lst2[i]
  elif lst2[i]>max:
    max=lst2[i]
x=lst2.index(max)
print(f'Largest number in the list is {max} which was found at index {x}.')

Enter a string containing numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Largest number in the list is 13 which was found at index 1.

In [ ]:
s = input("Enter a string containing numbers separated by commas: ")
lst1 = s.split(", ")
lst2 = []
for i in lst1:
  lst2.append(int(i))
print("My list:",lst2)
max=0
for i in range(len(lst2)):
  if i==0:
    max=lst2[i]
  elif lst2[i]>max:
    max=lst2[i]
x=0
for i in lst2:
  if i!=max:
    x+=1
  else:
    break
print(f'Largest number in the list is {max} which was found at index {x}.')

Enter a string containing numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Largest number in the list is 13 which was found at index 1.

In [ ]:
s = input("Enter a string containing numbers separated by commas: ")
x = ''
lst = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    lst.append(int(x))
    x=''
lst.append(int(x))
max=0
c = None
for i in range(len(lst)):
  if i==0:
    max=lst[i]
  elif lst[i]>max:
    max=lst[i]
    c = i
print(f'My list: {lst} \nLargest number in the list is {max} which was found at index {c}.')

Enter a string containing numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Largest number in the list is 13 which was found at index 1.

In [ ]:
s = input("Enter a string containing numbers separated by commas: ")
x = ''
lst = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    lst.append(int(x))
    x=''
lst.append(int(x))
max=0
for i in range(len(lst)):
  if i==0:
    max=lst[i]
  elif lst[i]>max:
    max=lst[i]
c=0
for i in lst:
  if i!=max:
    c+=1
  else:
    break
print(f'My list: {lst} \nLargest number in the list is {max} which was found at index {c}.')

Enter a string containing numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Largest number in the list is 13 which was found at index 1.

#Task 7

In [ ]:
s1=input("List_one : ")
s2=input("List_two : ")
s1=s1[1:-1]
s2=s2[1:-1]
l1=[int(i) for i in s1.split(', ')]
l2=[int(i) for i in s2.split(', ')]

print(l1[:-1]+l2)

List_one : [1, 4, 7, 5]
List_two : [6, 1, 3, 9]
[1, 4, 7, 6, 1, 3, 9]

In [ ]:
s1=input("List_one : ")
s2=input("List_two : ")
s1=s1[1:-1]
s2=s2[1:-1]
s1=s1.split(", ")
s2=s2.split(", ")
l1=[]
l2=[]
for i in s1:
  l1.append(int(i))
for i in s2:
  l2.append(int(i))

print(l1[:-1]+l2)

List_one : [1, 4, 7, 5]
List_two : [6, 1, 3, 9]
[1, 4, 7, 6, 1, 3, 9]

In [ ]:
s1=input("List_one : ")
s2=input("List_two : ")
s1=s1[1:-1]
s2=s2[1:-1]
l1=[]
l2=[]
x=''
y=''
for i in s1:
  if i!=' ' and i!=',':
    x+=i
  elif i==' ':
    l1.append(x)
    x=''
l1.append(x)
for i in s2:
  if i!=' ' and i!=',':
    y+=i
  elif i==' ':
    l2.append(y)
    y=''
l2.append(y)
l3=[]
l4=[]
for i in l1:
  l3.append(int(i))
for i in l2:
  l4.append(int(i))

print(l3[:-1]+l4)

List_one : [1, 4, 7, 5]
List_two : [6, 1, 3, 9]
[1, 4, 7, 6, 1, 3, 9]

In [ ]:
l1 = [1, 4, 7, 5]
l2 = [6, 1, 3, 9]
l1.pop(-1)
l1.extend(l2)
print(l1)

[1, 4, 7, 6, 1, 3, 9]

In [ ]:
l1 = [1, 4, 7, 5]
l2 = [6, 1, 3, 9]
print(l1[:-1]+l2)

[1, 4, 7, 6, 1, 3, 9]

#Task 8

In [ ]:
s1=input("list_one = ")
s2=input("list_two = ")
s1=s1[1:-1]
s2=s2[1:-1]
l1=[int(i) for i in s1.split(', ')]
l2=[int(i) for i in s2.split(', ')]
l3=[]
for i in l1:
  if i%2==0:
    l3.append(i)
for i in l2:
  if i%2==0:
    l3.append(i)
print(l3)

list_one = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two = [10, 11, 12, -13, -14, -15, -16]
[2, 4, 6, 8, 10, 12, -14, -16]

In [ ]:
s1=input("list_one = ")
s2=input("list_two = ")
s1=s1[1:-1]
s2=s2[1:-1]
s1=s1.split(", ")
s2=s2.split(", ")
l1=[]
l2=[]
for i in s1:
  l1.append(int(i))
for i in s2:
  l2.append(int(i))
l3=[]
for i in l1:
  if i%2==0:
    l3.append(i)
for i in l2:
  if i%2==0:
    l3.append(i)
print(l3)

list_one = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two = [10, 11, 12, -13, -14, -15, -16]
[2, 4, 6, 8, 10, 12, -14, -16]

In [ ]:
s1=input("List_one : ")
s2=input("List_two : ")
s1=s1[1:-1]
s2=s2[1:-1]
l1=[]
l2=[]
x=''
y=''
for i in s1:
  if i!=' ' and i!=',':
    x+=i
  elif i==' ':
    l1.append(x)
    x=''
l1.append(x)
for i in s2:
  if i!=' ' and i!=',':
    y+=i
  elif i==' ':
    l2.append(y)
    y=''
l2.append(y)
l3=[]
l4=[]
for i in l1:
  l3.append(int(i))
for i in l2:
  l4.append(int(i))
l5=[]
for i in l3:
  if i%2==0:
    l5.append(i)
for i in l4:
  if i%2==0:
    l5.append(i)
print(l5)

List_one : [1, 2, 3, 4, 5, 6, 7, 8, 9]
List_two : [10, 11, 12, -13, -14, -15, -16]
[2, 4, 6, 8, 10, 12, -14, -16]

#Task 9

In [ ]:
s=input("String of numbers separated by spaces: ")
x=''
l1=[]
for i in s:
  if i!=' ':
    x+=i
  else:
    l1.append(int(x))
    x=''
l1.append(int(x))
print("Original list:",l1)
l2=[]
for i in l1:
  if i%2!=0:
    l2.append(i)
print("Modified list:",l2)

String of numbers separated by spaces: 7 12 4 55 96 2 11 61 33 42
Original list: [7, 12, 4, 55, 96, 2, 11, 61, 33, 42]
Modified list: [7, 55, 11, 61, 33]

#Task 10

In [ ]:
l1=[int(i) for i in input("String of numbers separated by commas: ").split(', ')]
l2=[]
for i in l1:
  if i not in l2:
    l2.append(i)

print('Input list:',l1)
print('Modified list:',l2)

String of numbers separated by commas: 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4
Input list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]
Modified list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
s = input("String of numbers separated by commas: ")
s = s.split(', ')
l1=[]
for i in s:
  l1.append(int(i))
l2=[]
for i in l1:
  if i not in l2:
    l2.append(i)

print('Input list:',l1)
print('Modified list:',l2)

String of numbers separated by commas: 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4
Input list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]
Modified list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
s = input("String of numbers separated by commas: ")
x = ''
lst1 = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    lst1.append(int(x))
    x=''
lst1.append(int(x))
lst2 = []
for i in lst1:
  if i not in lst2:
    lst2.append(i)
print('Input list:',lst1)
print('Modified list:',lst2)

String of numbers separated by commas: 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4
Input list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]
Modified list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#Task 11

In [ ]:
s1=input("List_one : ")
s1=s1[1:-1]
s2=input("List_two : ")
s2=s2[1:-1]
l1=[int(i) for i in s1.split(', ')]
l2=[int(i) for i in s2.split(', ')]
for i in l1:
  if i in l2:
    x=True
    break
  else:
    x=False
if x==True:
  print('True')
else:
  print('False')

List_one : [1, 4, 3, 2, 5]
List_two : [8, 7, 6, 9]
False

In [ ]:
s1=input("List_one : ")
s1=s1[1:-1]
s1=s1.split(', ')
s2=input("List_two : ")
s2=s2[1:-1]
s2=s2.split(', ')
l1=[]
l2=[]
for i in s1:
  l1.append(int(i))
for i in s2:
  l2.append(int(i))
for i in l1:
  if i in l2:
    x=True
    break
  else:
    x=False
if x==True:
  print('True')
else:
  print('False')

List_one : [1, 4, 3, 2, 5]
List_two : [8, 7, 6, 9]
False

In [ ]:
s1=input("List_one : ")
s2=input("List_two : ")
s1=s1[1:-1]
s2=s2[1:-1]
l1=[]
l2=[]
x=''
y=''
for i in s1:
  if i!=' ' and i!=',':
    x+=i
  elif i==' ':
    l1.append(x)
    x=''
l1.append(x)
for i in s2:
  if i!=' ' and i!=',':
    y+=i
  elif i==' ':
    l2.append(y)
    y=''
l2.append(y)
l3=[]
l4=[]
for i in l1:
  l3.append(int(i))
for i in l2:
  l4.append(int(i))
for i in l3:
  if i in l4:
    x=True
    break
  else:
    x=False
if x==True:
  print('True')
else:
  print('False')

List_one : [1, 4, 3, 2, 5]
List_two : [8, 7, 6, 9]
False

#Task 12 (Tracing)

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while(index1<10):
  myList[index1] = index1+4
  index2 = 1
  while(index2<index1):
      myList[index1] = myList[index1] + myList[index2]-index1
      index2 = index2+1
  print(myList[index1])
  index1 = index1+1

5
9
15
25
43
77
143
273
531

#Task 13 (Tracing)

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while (index1 < 10):
  myList[index1] = index1 + 4
  index2 = 1
  while (index2 < index1):
    myList[index1] = myList[index1-1] - myList[index2-1] - index1
    index2 = index2 + 1
  print(myList[index1])
  index1 = index1 + 1

5
3
-5
-12
-12
-6
-1
-3
-11

#Task 14 (Tracing)

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while(index1<10):
  myList[index1] = index1+2
  index2 = 1
  while(index2<index1):
    myList[index1] = b[index1]+myList[index2]-index1
    index2 = index2+1
  print(myList[index1])
  index1 = index1+1

3
5
7
9
11
13
15
17
19

#Task 15 (Tracing)

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while (index1 < 10):
  myList[index1] = index1 + 1
  index2 = 1
  while (index2 < index1):
    myList[index1] = b[index2-1] + myList[index2] - index1
    index2 = index2 + 1
  print(myList[index1])
  index1 = index1 + 1

2
0
-1
-5
-11
-22
-40
-70
-119

#Task 16 (Ungraded)

In [ ]:
l1=[int(i) for i in input("String of numbers separated by commas: ").split(', ')]
print('My list:',l1)
max = 0
max2 = 0
for i in range(len(l1)):
  if i==0:
    max=l1[i]
    max2=l1[i]
  elif l1[i]>max:
    max=l1[i]
  elif max>l1[i]>max2:
    max2=l1[i]
print(f'Second largest number in the list is {max2} which was found at index {l1.index(max2)}.')

String of numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Second largest number in the list is 10 which was found at index 3.

In [ ]:
s = input("String of numbers separated by commas: ")
s = s.split(', ')
l1=[]
for i in s:
  l1.append(int(i))
print('My list:',l1)
max = 0
max2 = 0
for i in range(len(l1)):
  if i==0:
    max=l1[i]
    max2=l1[i]
  elif l1[i]>max:
    max=l1[i]
  elif max>l1[i]>max2:
    max2=l1[i]
print(f'Second largest number in the list is {max2} which was found at index {l1.index(max2)}.')

String of numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Second largest number in the list is 10 which was found at index 3.

In [ ]:
s = input("String of numbers separated by commas: ")
x = ''
l1 = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    l1.append(int(x))
    x=''
l1.append(int(x))
print('My list:',l1)
max = 0
max2 = 0
c = 0
for i in range(len(l1)):
  if i==0:
    max=l1[i]
    max2=l1[i]
  elif l1[i]>max:
    max=l1[i]
  elif max>l1[i]>max2:
    max2=l1[i]
    c = i
print(f'Second largest number in the list is {max2} which was found at index {c}.')

String of numbers separated by commas: 7, 13, 2, 10, 6, -11, 0
My list: [7, 13, 2, 10, 6, -11, 0]
Second largest number in the list is 10 which was found at index 3.

#Task 17 (Ungraded)

In [ ]:
l = [int(i) for i in input("String of numbers separated by commas: ").split(', ')]
print('My list',l)
min=0
max=0
for i in range(len(l)):
  if i==0:
    min=l[i]
    max=l[i]
  elif l[i]<min:
    min=l[i]
  elif l[i]>max:
    max=l[i]
print(f'Smallest number in the list is {min} which was found at index {l.index(min)}')
print(f'Largest number in the list is {max} which was found at index {l.index(max)}')

String of numbers separated by commas: 7, 13, -5, 10, 6
My list [7, 13, -5, 10, 6]
Smallest number in the list is -5 which was found at index 2
Largest number in the list is 13 which was found at index 1

In [ ]:
s = input("String of numbers separated by commas: ")
s = s.split(', ')
l = []
for i in s:
  l.append(int(i))
print('My list',l)
min=0
max=0
for i in range(len(l)):
  if i==0:
    min=l[i]
    max=l[i]
  elif l[i]<min:
    min=l[i]
  elif l[i]>max:
    max=l[i]
print(f'Smallest number in the list is {min} which was found at index {l.index(min)}')
print(f'Largest number in the list is {max} which was found at index {l.index(max)}')

String of numbers separated by commas: 7, 13, -5, 10, 6
My list [7, 13, -5, 10, 6]
Smallest number in the list is -5 which was found at index 2
Largest number in the list is 13 which was found at index 1

In [ ]:
s = input("String of numbers separated by commas: ")
x = ''
l = []
for i in s:
  if i!=',' and i!=' ':
    x+=i
  elif i==' ':
    l.append(int(x))
    x=''
l.append(int(x))
print('My list:',l)
min=0
max=0
cmx=0
cmn=0
for i in range(len(l)):
  if i==0:
    min=l[i]
    max=l[i]
  elif l[i]<min:
    min=l[i]
    cmn=i
  elif l[i]>max:
    max=l[i]
    cmx=i
print(f'Smallest number in the list is {min} which was found at index {cmn}')
print(f'Largest number in the list is {max} which was found at index {cmx}')

String of numbers separated by commas: 7, 13, -5, 10, 6
My list: [7, 13, -5, 10, 6]
Smallest number in the list is -5 which was found at index 2
Largest number in the list is 13 which was found at index 1

#Task 18 (Ungraded)

In [ ]:
s1=[i for i in input("List_One: ").split(', ')]
s2=[i for i in input("List_Two: ").split(', ')]
l=[]
for i in s1:
  if i in s2:
    l.append(i)

print(l)

List_One: 1, 3, A, H, P
List_Two: A, G, 1, P, O
['1', 'A', 'P']

In [ ]:
s1=input("List_One: ")
s2=input("List_Two: ")
s1=s1.split(', ')
s2=s2.split(', ')
l=[]
for i in s1:
  if i in s2:
    l.append(i)

print(l)

List_One: 1, 3, A, H, P
List_Two: A, G, 1, P, O
['1', 'A', 'P']

In [ ]:
s1=input("List_One: ")
s2=input("List_Two: ")
l1=[]
l2=[]
x=''
y=''
for i in s1:
  if i!=' ' and i!=',':
    x+=i
  elif i==' ':
    l1.append(x)
    x=''
l1.append(x)
for i in s2:
  if i!=' ' and i!=',':
    y+=i
  elif i==' ':
    l2.append(y)
    y=''
l2.append(y)
l=[]
for i in l1:
  if i in l2:
    l.append(i)
print(l)

List_One: 1, 3, A, H, P
List_Two: A, G, 1, P, O
['1', 'A', 'P']

#Task 19 (Ungraded)

In [ ]:
s1=input("list_one = ")
s1=s1[1:-1]
s2=input("list_two = ")
s2=s2[1:-1]
l1=[int(i) for i in s1.split(', ')]
l2=[int(i) for i in s2.split(', ')]
l3 = l1+l2
l4=[]
for i in l3:
  if i not in l4:
    l4.append(i)
print(l4)

list_one = [1, 2, 2, 4, 5, 5, 7, 99, 200, 303, 70]
list_two = [1, 1, 2, 3, 3, 3, 4, 5, 200, 500, -5]
[1, 2, 4, 5, 7, 99, 200, 303, 70, 3, 500, -5]

In [ ]:
s1=input("list_one = ")
s1=s1[1:-1]
s1=s1.split(', ')
s2=input("list_two = ")
s2=s2[1:-1]
s2=s2.split(', ')
l1=[]
for i in s1:
  l1.append(int(i))
l2=[]
for i in s2:
  l2.append(int(i))
l3 = l1+l2
l4=[]
for i in l3:
  if i not in l4:
    l4.append(i)
print(l4)

list_one = [1, 2, 2, 4, 5, 5, 7, 99, 200, 303, 70]
list_two = [1, 1, 2, 3, 3, 3, 4, 5, 200, 500, -5]
[1, 2, 4, 5, 7, 99, 200, 303, 70, 3, 500, -5]

In [ ]:
s1=input("list_one = ")
s1 = s1[1:-1]
s2=input("list_two = ")
s2 = s2[1:-1]
l1=[]
l2=[]
x=''
y=''
for i in s1:
  if i!=' ' and i!=',':
    x+=i
  elif i==' ':
    l1.append(int(x))
    x=''
l1.append(int(x))
for i in s2:
  if i!=' ' and i!=',':
    y+=i
  elif i==' ':
    l2.append(int(y))
    y=''
l2.append(int(y))
l3 = l1+l2
l4 = []
for i in l3:
  if i not in l4:
    l4.append(i)
print(l4)

list_one = [1, 2, 2, 4, 5, 5, 7, 99, 200, 303, 70]
list_two = [1, 1, 2, 3, 3, 3, 4, 5, 200, 500, -5]
[1, 2, 4, 5, 7, 99, 200, 303, 70, 3, 500, -5]

#Task 20 (Ungraded)

In [ ]:
s = input("String: ")
print('Original data:',s)
s = s.strip()
s = s[1:-1]
print('After removing square brackets:',s)
x = s.split(',')
print('Numbers in string format with extra white spaces:',x)
y=''
for i in s:
  if i!=' ':
    y+=i
l = [int(i) for i in y.split(',')]
print('Final data (numbers in list format):',l)

String:       [1,   2   ,         3,   50,   4]
Original data:       [1,   2   ,         3,   50,   4]
After removing square brackets: 1,   2   ,         3,   50,   4
Numbers in string format with extra white spaces: ['1', '   2   ', '         3', '   50', '   4']
Final data (numbers in list format): [1, 2, 3, 50, 4]

In [ ]:
s = input("String: ")
print('Original data:',s)
s = s.strip()
s = s[1:-1]
print('After removing square brackets:',s)
s = s.split(',')
print('Numbers in string format with extra white spaces:',s)
l1 = []
for i in s:
  l1.append(i+' ')
l2 = []
x=''
for i in l1:
  for j in i:
    if j!=' ':
      x+=j
    else:
      l2.append(x)
      x=''
l3=[]
for i in l2:
  if i!='':
    l3.append(int(i))
print('Final data (numbers in list format):',l3)

String:       [1,   2   ,         3,   50,   4]
Original data:       [1,   2   ,         3,   50,   4]
After removing square brackets: 1,   2   ,         3,   50,   4
Numbers in string format with extra white spaces: ['1', '   2   ', '         3', '   50', '   4']
Final data (numbers in list format): [1, 2, 3, 50, 4]

#Task 21 (Ungraded)

In [ ]:
s = input("String of numbers separated by commas: ")
x = ''
for i in s:
  if ord(i)!=32:
    x+=i
l1=[int(i) for i in x.split(',')]
print("Given numbers in the list:",l1)
l2=[]
for i in l1:
  if i not in l2:
    l2.append(i)
print("List without any dupliacte values:",l2)

String of numbers separated by commas: 0, 0, 1, 2, 3, 4,      4, 5, 6, 6, 6,      7, 8, 9, 4,         4
Given numbers in the list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]
List without any dupliacte values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
s = input("String of numbers separated by commas: ")
x = ''
for i in s:
  if ord(i)!=32:
    x+=i
l1=[]
x=x.split(',')
for i in x:
  l1.append(int(i))
print("Given numbers in the list:",l1)
l2=[]
for i in l1:
  if i not in l2:
    l2.append(i)
print("List without any dupliacte values:",l2)

String of numbers separated by commas: 0, 0, 1, 2, 3, 4,      4, 5, 6, 6, 6,      7, 8, 9, 4,         4
Given numbers in the list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]
List without any dupliacte values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]